#pragma once
#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_USB_DETECT
#define SPLIT_USB_TIMEOUT 2500
#define SPLIT_USB_TIMEOUT_POLL 10
